### ISSUE TITLE
Do we need input splits as new S3 objects?

### ISSUE THREAD

**Issue by danilop** [bcongdon/corral#5]
Since Amazon S3 supports the HTTP Range header in the GET Object API [1], do we really need to split the input files? For Mappers, the framework could just invoke Lambda functions asynchronously with an input file and a byte range to process.

[1] https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html

**Comment by bcongdon** [comment]
Input splits are already implemented this way. 🙂An input split is just a S3 object handle (path), with a range of bytes -- there's no copy done to create new S3 objects from splits. 

https://github.com/bcongdon/corral/blob/master/split.go#L15
