### ISSUE TITLE
Fail to achieve concurrency

### ISSUE THREAD

**Issue by ShagunParikh** [bcongdon/corral#6]
[masterFile.txt](https://github.com/bcongdon/corral/files/2939774/masterFile.txt)

Above is the input file for the map. Now I was hoping that it would get split per line. Meaning, there shall be 10 lambda functions running concurrently, considering the input file has 10 new lines. 

But it doesn't. Instead, Only a single **lambda function** is running which executes each line sequentially. Hence it **fails to achieve concurrency**.

Here is my code:

```
func main() {
	job := corral.NewJob(wordCount{}, wordCount{})

	options := []corral.Option{
		corral.WithSplitSize(12),
		corral.WithMapBinSize(12),
	}

	driver := corral.NewDriver(job, options...)
	driver.Main()
}
```

It does show multiple maps (example 1/10, 2/10 etc) while I execute it locally. But when I deploy it to aws lambda, it only executes 1 map/function. 

Any kind of help would be really appreciated.

**Comment by bcongdon** [comment]
I was able to use your example code/input and have 10 parallel lambdas using the following invocation:

```
go run main.go -v --lambda --out s3://${AWS_TEST_BUCKET} s3://${AWS_TEST_BUCKET}/master_file.txt
```

(Where `${AWS_TEST_BUCKET}` is the bucket you've stored your input in)

Can you provide the command you're invoking the job with as well as the output log? (The verbose log would be helpful)

**Comment by ShagunParikh** [comment]
Firstly, Thanks alot for the quick reply

Here is more information:

**Command:**

`Main --lambda s3://{BuckName}/masterFile.txt --out s3://{BuckName}/`

where **Main** is the exe file generated by `go build` command


**AWS Lambda Logs:**

> START RequestId: 6e4992fe-43d3-454e-b7fe-629955cf57ab Version: $LATEST
> File - file_0.json
> File - file_1.json
> File - file_2.json
> File - file_3.json
> File - file_4.json
> File - file_5.json
> File - file_6.json
> File - file_7.json
> File - file_8.json
> File - file_9.json
> END RequestId: 6e4992fe-43d3-454e-b7fe-629955cf57ab
> REPORT RequestId: 6e4992fe-43d3-454e-b7fe-629955cf57ab	Duration: 1762.65 ms	Billed Duration: 1800 ms Memory Size: 1500 MB	Max Memory Used: 112 MB	
> START RequestId: 1b11b786-1df6-48f8-bed4-703186fcb955 Version: $LATEST
> END RequestId: 1b11b786-1df6-48f8-bed4-703186fcb955
> REPORT RequestId: 1b11b786-1df6-48f8-bed4-703186fcb955	Duration: 266.66 ms	Billed Duration: 300 ms Memory Size: 1500 MB	Max Memory Used: 112 MB

**Comment by ShagunParikh** [comment]
@bcongdon hoping and waiting for another quick reply :)

**Comment by bcongdon** [comment]
Hi, I wish I had better news, but I'm still unable to reproduce the error you're having. 😕 (When I deploy, I get the correct number of jobs)

The only thing I can think of would be to try undeploying everything (`Main --undeploy`), reuploading inputs to S3, and then redeploying.

Also, I'd double check that you're using the latest version of `corral`, a reasonably up-to-date version of `go` (I tested using `1.11.4`), etc.

---

I'd also make the general suggestion that corral wasn't _really_ built to handle really small input splits like this. Optimally, you'd want to give splits that are as big as possible while allowing the lambda to still process its entire split before timing out.

In principle there's nothing preventing you from using 12-byte input splits, but be warned that `corral` wasn't designed to work optimally for this (and having such small splits probably won't scale well to large inputs)

In your example, it looks like you might be loading files in the map phase? If your use-case supports it, it might be better to feed all the input files as inputs to the map phase. (i.e. `Main file*.json`). Without more context, I'm not sure if this is what you're trying to do. 🙂

**Comment by ShagunParikh** [comment]
Hi,

Regarding _"In your example, it looks like you might be loading files in the map phase?"_ - Yes, I am loading files in the map because I have thousands of file which I want to process parallelly. So that's the use-case. of using corral. 

Anyways,  I am checking the versions and other possible ways to resolve the issue. Will let you know if I achieve success.

**Comment by ShagunParikh** [comment]
Undeploying everything, reinstalling dependency and rebuilding everything from the scratch magically solved the concurrency issue.  🥇 

But it is not creating the exact number of maps as the number of new lines, as you warned. But I wish there was a way to split the input merely on the basis on new lines and not per bytes. Hoping for an update :-)

But thanks anyways!

**Comment by ShagunParikh** [comment]
@bcongdon 1 more question - `Main -v --lambda s3://{BuckName}/masterFile.txt --out s3://{BuckName}/ ` deploys to lambda function and executes it. IS there a way to execute the already deployed function with input file as argument?

**Comment by bcongdon** [comment]
The `--lambda` flag only redeploys if your code has changed, so you can do something like 


`Main -v --lambda --out s3://{OutputBucket}/ s3://{InputBucket}/masterFile1.txt`

... followed immediately by

`Main -v --lambda --out s3://{OutputBucket}/ s3://{InputBucket}/masterFile2.txt`

and (assuming you didn't make any code changes) the same Lambda will be used.

Note that the last argument is a list of input files, so you could even do something like this to act on both files with 1 run:

`Main -v --lambda --out s3://{OutputBucket}/ s3://{InputBucket}/masterFile1.txt s3://{InputBucket}/masterFile2.txt`

---

Currently there isn't a flag that explicitly skips the compilation/deployment step. I think this could be useful if you have really big jobs and don't want to compile everything each time you run it. I created #8 to track this idea.
