### ISSUE TITLE
Passing a value to map functions

### ISSUE THREAD

**Issue by ShagunParikh** [bcongdon/corral#9]
Hi,

Your framework is extremely useful for parallel processing. I have been exploring it and using it.

*But i was wondering if there is a way to pass some value to every map functions?*

Suppose i have a large file that contains lacs of words.

Now i want to pass an input word and check if that word exists in the file and if yes then whats the count of that word.
In this case i need a way to pass that input word to map functions.

**Comment by bcongdon** [comment]
This sounds effectively like a map-side join.

You could accomplish this by putting a pointer to the list of words in your job struct.

i.e.
```go
type myJob struct{
	words *[]string
}

func (job myJob) Map(key, value string, emitter corral.Emitter) {
	for _, word := range strings.Fields(value) {
		// Pseudocode
		if contains(job.words, word) {
			emitter.Emit(word, "")
		}
	}
}

func (job myJob) Reduce(...) {...}

func main() {
	jobStruct := myJob{}
	jobStruct.words = loadWordsFile()

	job := corral.NewJob(jobStruct, jobStruct)

	driver := corral.NewDriver(job)
	driver.Main()
}
```

**Comment by ShagunParikh** [comment]
Yes, that worked. Thanks :)

**Comment by ShagunParikh** [comment]
func (job myJob) Map(key, value string, emitter corral.Emitter) {
	for _, word := range strings.Fields(value) {
		// Pseudocode
		if contains(job.words, word) {
			emitter.Emit(word, "")
		}
	}
}


Here `*job.words ` is aways blank. :(

**Comment by bcongdon** [comment]
What modifications did you make? Since you changed the source, I don't really have a good way of knowing what might be going wrong
